### ISSUE TITLE
Deprecated: openssl_free_key()

### ISSUE THREAD

**Issue by csedo** [ferling/kh-vpos#1]
Hi!

I'm very happy to use this repo for our complex ecommerce webshop but one function is deprecated. Coould you delete it from the repo? It does not have effect anymore in php 8.

https://www.php.net/manual/en/function.openssl-free-key.php

**Comment by tolnaiz** [comment]
Hi!

I will keep it for backward compatibility, but it won't be called on php 8.0 and above.
I also updated composer.json to support php8.
